CREATE TABLE IF NOT EXISTS companies (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CNPJ VARCHAR(255),
    NOME_FANTASIA VARCHAR(255),
    SITUACAO_CADASTRAL INT,
    CNAE VARCHAR(255),
    UF VARCHAR(2),
    Municipio INT
);