version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: conecta-vagas-db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: conectavagas
    ports:
      - "127.0.0.1:80:3306"
    volumes:
      - conecta_vagas_db:/var/lib/mysql

  api:
    container_name: conecta-vagas-api
    build: .
    env_file:
      - .env
    environment:
      DB_URL: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false&requireSSL=false
      SPRING_PROFILES_ACTIVE: ${APP_ENV}
    ports:
      - 127.0.0.1:${API_PORT}:${API_PORT}
    depends_on:
      - db

volumes:
  conecta_vagas_db: