version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: conecta-vagas-db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_USER}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 127.0.0.1:${DB_PORT}:3306
    volumes:
      - conecta_vagas_db:/var/lib/mysql
    networks:
      - conecta_vagas_network

  api:
    container_name: conecta-vagas-api
    build: .
    env_file:
      - .env
    environment:
      DB_URL: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false&requireSSL=false
    ports:
      - 127.0.0.1:${API_PORT}:${API_PORT}
    depends_on:
      - db
    networks:
      - conecta_vagas_network

volumes:
  conecta_vagas_db:

networks:
  conecta_vagas_network:
    name: conecta_vagas_shared_network